import { test, expect } from '@playwright/test';

test('Loads the Global Discovery Portal Header', async ({ page }) => {
  // Navigate to root (Landing Page)
  await page.goto('/');

  // Expect the header logo text to be present
  await expect(page.locator('.header-logo')).toContainText('Enterprise Documentation');

  // Expect the theme toggle button to be present
  await expect(page.locator('.theme-toggle')).toContainText('Theme');
});

test('Successfully loads embedded markdown static images from Backend', async ({ page }) => {
  // Navigate directly to the newly authored EKS Architecture page
  await page.goto('/docs/infrastructure/compute/eks/architecture');
  await page.waitForTimeout(2000); // Give Angular time to fetch and paint the markdown JSON

  // Wait for the specific EKS markdown image to be physically injected into the DOM
  const imageElement = page.locator('img[src="http://localhost:3000/api/assets/infrastructure/compute/eks/architecture.png"]');
  await expect(imageElement).toBeVisible();

  // Evaluate the raw image binary loaded successfully (not a broken 404 silhouette)
  const isImageLoaded = await imageElement.evaluate((img: HTMLImageElement) => {
    return img.complete && img.naturalWidth > 0;
  });

  expect(isImageLoaded).toBeTruthy();
});

test('Successfully renders Shiki syntax highlighting blocks with inline CSS tokens', async ({ page }) => {
  // Navigate to the Setup page containing the Terraform (HCL) block
  await page.goto('/docs/infrastructure/compute/eks/setup');
  await page.waitForTimeout(2000);

  // Verify the custom Shiki DOM container was injected by the Backend API
  const shikiPreElement = page.locator('pre.shiki');
  await expect(shikiPreElement).toBeVisible();

  // Look for the specific nested token span generated by the Shiki WASM grammar engine
  // Shiki inherently assigns inline style CSS overrides to each token.
  // We grab the first span inside the code block to prove tokenization occurred.
  const shikiTokenSpan = shikiPreElement.locator('span[style]').first();
  await expect(shikiTokenSpan).toBeVisible();

  // Extract the inline styles applied by Shiki over the wire
  const inlineStyles = await shikiTokenSpan.getAttribute('style');
  expect(inlineStyles).toContain('--shiki-light');
});
