import { DocumentNode, MarkdownMetadata } from '@tmp-dac/shared-types';

export { DocumentNode, MarkdownMetadata };

export abstract class StorageProvider {
    /**
     * Reads raw markdown content from the underlying storage mechanism.
     * @param path The relative path to the markdown file (e.g. 'domain/system/product/index.md')
     */
    abstract getDocumentContent(path: string): Promise<string | any>;

    /**
     * Resolves a collection of all available products and their nested file structures.
     * Required for building the Navigation Portals.
     */
    abstract getCatalogTree(): Promise<DocumentNode[]>;

    /**
     * Retrieves the serialized search index generated by the CLI out of the dist artifacts folder.
     */
    abstract getSearchIndex(): Promise<any>;
}
